### PR TITLE
add METATYPE_IMAGEJPG (not yet functional)

### PR DESCRIPTION
**Pull request by eudoxos**
Hi, I tried to add a custom node type to QMetaType so that the UA client (UaExpert) will interpret a ByteString as IMAGEJPG. I did not succeed, it seems that despite setting `setDataType(METATYPE_IMAGEJPG)` on the node (which is reflected in the UaExpert client), passing encoded JPG blob via `setValue(QVariant(QByteArray(...)))` will "downgrade" node type to plain ByteString. When I call `setValue(QVariant(QByteArray(...)),METATYPE_IMAGEJPG)`, I see this message:
```
[2019-07-18 13:34:47.646 (UTC+0200)] info/session	Connection 0 | SecureChannel 0 | Session g=00000001-0000-0000-0000-000000000000 | WriteRequest returned status code BadTypeMismatch
```
Where is the problem?

### CODE REVIEW

**Comment by juangburgos** [comment]
Hi, Can you post the code that you are using to test your new METATYPE_IMAGEJPG data type, so I can reproduce the error message you get?

**Comment by eudoxos** [comment]
Here you go:

``` c++
#include<QCoreApplication>
#include<QUaServer>
#include<QFile>


int main(int argc, char** argv){
	QCoreApplication app(argc, argv);
	QUaServer server;
	QUaFolderObject *root=server.objectsFolder();
	QUaFolderObject* folder=root->addFolderObject();
	folder->setDisplayName("myfolder");
	folder->setBrowseName("myfolder");
	QUaBaseDataVariable* var=root->addBaseDataVariable("ns=1;s=myvar");
	var->setDisplayName("myvar");
	var->setBrowseName("myvar");
	var->setDataType(METATYPE_IMAGEJPG);
	#if 0
		QFile i("/tmp/example.jpg");
		i.open(QIODevice::ReadOnly);
		QByteArray arr=i.readAll();
	#else
		// smallest valid JPG to test
		unsigned char jpeg_jpg[] = {
			0xff, 0xd8, 0xff, 0xdb, 0x00, 0x43, 0x00, 0x03, 0x02, 0x02, 0x02, 0x02,
			0x02, 0x03, 0x02, 0x02, 0x02, 0x03, 0x03, 0x03, 0x03, 0x04, 0x06, 0x04,
			0x04, 0x04, 0x04, 0x04, 0x08, 0x06, 0x06, 0x05, 0x06, 0x09, 0x08, 0x0a,
			0x0a, 0x09, 0x08, 0x09, 0x09, 0x0a, 0x0c, 0x0f, 0x0c, 0x0a, 0x0b, 0x0e,
			0x0b, 0x09, 0x09, 0x0d, 0x11, 0x0d, 0x0e, 0x0f, 0x10, 0x10, 0x11, 0x10,
			0x0a, 0x0c, 0x12, 0x13, 0x12, 0x10, 0x13, 0x0f, 0x10, 0x10, 0x10, 0xff,
			0xc9, 0x00, 0x0b, 0x08, 0x00, 0x01, 0x00, 0x01, 0x01, 0x01, 0x11, 0x00,
			0xff, 0xcc, 0x00, 0x06, 0x00, 0x10, 0x10, 0x05, 0xff, 0xda, 0x00, 0x08,
			0x01, 0x01, 0x00, 0x00, 0x3f, 0x00, 0xd2, 0xcf, 0x20, 0xff, 0xd9
		};
		QByteArray arr=QByteArray::fromRawData((const char*)&jpeg_jpg,sizeof(jpeg_jpg));
	#endif
	var->setValue(QVariant(arr),METATYPE_IMAGEJPG);
	server.start();
	return app.exec(); 
}
```

**Comment by juangburgos** [comment]
Going down the rabbit hole inside open62541, it seems the error gets generated in the `compatibleDataType` function:

```c
UA_Boolean
compatibleDataType(UA_Server *server, const UA_NodeId *dataType,
                   const UA_NodeId *constraintDataType, UA_Boolean isValue)
``` 

It compares if the type of tha value `dataType` (`UA_NS0ID_BYTESTRING`, or 15) matches the datatype of the variable `constraintDataType` (`UA_NS0ID_IMAGEJPG`, or 2002). And it seems that this function determines that the types are not compatible. Are you sure per the standard that image encodings are exactly the same as for Bytestrings?

I tried to quickly find in the open62541 repo if somebody has been able to send an image, but so far I could not find any example. If we could find some successfull example of open62541 sending an image, then I could modify QUaServer to support this.

**Comment by juangburgos** [comment]
I finally found some info:

<https://groups.google.com/forum/#!topic/open62541/qK0lq6wwqzI>

Chekc out the changes I pushed to your image branch. Turns out you needed the FULL namespace in the amalgamation:

```
cmake -DUA_ENABLE_AMALGAMATION=ON -DUA_NAMESPACE_ZERO=FULL .. -G "Visual Studio 15 2017 Win64"
```

Then you get `UA_TYPES_IMAGEJPG` in `open52541.h` so you can use it in `uaTypeFromQType` as:

```c++
case METATYPE_IMAGEJPG:
			return &UA_TYPES[UA_TYPES_IMAGEJPG];
```

**Comment by eudoxos** [comment]
Excellent, thanks!

**Comment by eudoxos** [comment]
Just tested with UaExpert , using its Image Viewer plugin, getting: `Unsupported node dropped (ValueRank = -2, DataType=ImageJPG)`. So the type is transferred correctly now but I don't see the image anyway. So the main motivation for this feature is vanishing. Plus, the full amalgamation is almost 10MB size, maybe better leave QUaServer without images after all...

**Comment by juangburgos** [comment]
Maybe UaExpert requires an specific ValueRank for images. I find UaExpert to be very picky sometimes when displaying data. I had issues with enums for example. But myabe if you try other ValueRanks, one might work to display the image.

In QUaServer I opted out to set it to -2 (`UA_VALUERANK_ANY`) because once you set it you cannot change it, and UA_VALUERANK_ANY it works most of the times. You could experiment changing [in here](https://github.com/juangburgos/QUaServer/blob/696912114c2515661873af2a73110ff54bb604fd/src/wrapper/quaserver.cpp#L1683), see if some other value works.

**Comment by eudoxos** [comment]
I wrote `setValueRank`, set `UA_VALUERANK_SCALAR`; JPG did not work at all, so I switched to PNG and now the image is recognized as image by UaExpert client.

Their demo server includes some image nodes, though curiously the image viewer cannot show their own JPG as image ;) (`Received ByteArray does not contain an image`). It can display only PNGs and BMPs, but not JPG or GIF.

There is also abstract format-agnostic image type (in amalgamation: `#define UA_NS0ID_IMAGE 30`)  which would presumably not need the full amalgamation. The demo server is serving an image this way, which is internally a PNG, but I cannot see how to instantiate it with open62541 as there is no `UA_TYPES_IMAGE`. That would be the best.

image

**Comment by juangburgos** [comment]
Since the abstract image is internally a PNG, couldnt you just use UA_TYPES_IMAGEPNG or what ever is the respective PNG type?

As for the Qt API what we could implement is just accept any format Qt accepts and internally convert all to PNG?

**Comment by eudoxos** [comment]
`UA_TYPES_IMAGEPNG` worked, good. For QPixmap, the problem is that it is a part of QtGUI, which means pulling that whole module just for image format conversion. Maybe only compile it conditionally

**Comment by eudoxos** [comment]
Plus using `UA_TYPES_PNG` means using full amalgamation is necessary.

**Comment by juangburgos** [comment]
Awesome! Yes, well actually I think using defines is the way to go. Take a quick look on how to enable events in QUaServer (which also require full amalgamation) and you will find it makes use of defines to enable the functinality. As long as we document properly how to enable it, I believe it would be a good solution for any interested user.

**Pull request closed without merging**
